on:
  workflow_call: {}
  push: {}

env:
  REGISTRY: ghcr.io

jobs:
  metadata:
    runs-on: ubuntu-latest
    steps:
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=schedule
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: dump meta
        run: |
          echo "# Dump \`meta\`"           >> $GITHUB_STEP_SUMMARY
          echo ""                          >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json"                >> $GITHUB_STEP_SUMMARY
          echo '${{ toJSON(steps.meta) }}' >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`"                    >> $GITHUB_STEP_SUMMARY
      
      - name: dump json
        run: |
          echo "# Dump \`meta.outputs.json\`"                     >> $GITHUB_STEP_SUMMARY
          echo ""                                                 >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json"                                       >> $GITHUB_STEP_SUMMARY
          echo '${{ toJSON(fromJson(steps.meta.outputs.json)) }}' >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`"                                           >> $GITHUB_STEP_SUMMARY

      - name: dump bake-file
        run: |
          echo "# Dump \`meta.bake-file\`" >> $GITHUB_STEP_SUMMARY
          echo ""                          >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`json"                >> $GITHUB_STEP_SUMMARY
          echo '${{ toJSON(steps.meta) }}' >> $GITHUB_STEP_SUMMARY
          cat ${{ steps.meta.bake-file }}  >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`"                    >> $GITHUB_STEP_SUMMARY

  debug:
    uses: ./.github/workflows/_debug.yml
